name: magma-mud
version: '3.07'
summary: The Magma Multi-User Dungeon (MUD) Engine
description: |
  Magma is an oldschool multi-user dungeon similar to what was popular in
  the 1990s. It runs a multiplayer text-based dungeon crawl game as a 
  telnet server on port 4001 by default. It has player-vs-player combat
  enabled as one of its core features.

grade: stable
confinement: strict

apps:
  magma:
    command: bin/magma
    environment:
      MAGMA_HOME: $SNAP_COMMON/magma/
    aliases: [magma]
    plugs: [network, network-bind]
    daemon: simple

parts:
  magma:
    source: https://github.com/xangis/magma
    source-type: git
    plugin: cmake
    build-packages: [g++]

